version: '3.8'

services:
  app:
    build: .
    container_name: node_api_server_prduction
    restart: always
    ports:
      # Map Port 8087 (เครื่องเรา) -> 4001 (Container)
      - "8087:4001"
    environment:
      - PORT=4001
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app_network_prd

networks:
  app_network_prd:
    driver: bridge